export const wowtruck_social_media_urls = {
  WOWTRUCK_YOUTUBE_URL:
    "https://www.youtube.com/@WowtruckTechnologies-ge9my/featured",
  WOWTRUCK_FACEBOOK_URL:
    "https://www.facebook.com/profile.php?id=100092548655727",
  WOWTRUCK_INSTAGRAM_URL: "https://www.instagram.com/wowtrucktechnologies/",
  WOWTRUCK_TWITTER_URL: "https://twitter.com/WowtruckTech",
  WOWTRUCK_LINKEDIN_URL: "https://www.linkedin.com/company/wow-trucks/",
  WOWTRUCK_CUSTOMER_APP_PLAY_STORE_URL:
    "https://play.google.com/store/apps/details?id=in.wowtruck.supplierapp",
  WOWTRUCK_CUSTOMER_APP_APPLE_STORE_URL:
    "https://apps.apple.com/in/app/wowtruck-customer-app/id1661769386",
};

export const trackloadConstants = {
  ADD_CONSIGNEE: "ADD_CONSIGNEE",
  ADD_CONSIGNEE_SUCCESS: "ADD_CONSIGNEE_SUCCESS",
  ADD_CONSIGNEE_FAILURE: "ADD_CONSIGNEE_FAILURE",
  ADD_CONSIGNOR: "ADD_CONSIGNOR",
  ADD_CONSIGNOR_SUCCESS: "ADD_CONSIGNOR_SUCCESS",
  ADD_CONSIGNOR_FAILURE: "ADD_CONSIGNOR_FAILURE",
  GENERATE_LR: "GENERATE_LR",
  GENERATE_LR_SUCCESS: "GENERATE_LR_SUCCESS",
  GENERATE_LR_FAILURE: "GENERATE_LR_FAILURE",
  REMOVE_CONSIGNEE: "REMOVE_CONSIGNEE",
  REMOVE_CONSIGNEE_SUCCESS: "REMOVE_CONSIGNEE_SUCCESS",
  REMOVE_CONSIGNOR: "REMOVE_CONSIGNOR",
  REMOVE_CONSIGNOR_SUCCESS: "REMOVE_CONSIGNOR_SUCCESS",
  RAISE_DISPUTE: "RAISE_DISPUTE",
};
export const newloadConstants = {
  PRICECALCULATE: "PRICECALCULATE",
  PRICECALCULATE_SUCESS: "PRICECALCULATE_SUCESS",
  PRICECALCULATE_FAILURE: "PRICECALCULATE_FAILURE",
  PRICECALCULATE_LODING: "PRICECALCULATE_LODING",
  CONFIRMBOOKING: "CONFIRMBOOKING",
  CONFIRMBOOKING_LODING: "CONFIRMBOOKING_LODING",
  CONFIRMBOOKING_FAILURE: "CONFIRMBOOKING_FAILURE",
  CONFIRMBOOKING_SUCESSS: "CONFIRMBOOKING_SUCESSS",
  GETTINGADDRESSLIST: "GETTINGADDRESSLIST",
  GETADDRESSLIST: "GETADDRESSLIST",
  ADDADDRESS: "ADDADDRESS",
  ADDADDRESS_FAILURE: "ADDADDRESS_FAILURE",
  FAILURE: "FAILURE",
  INTERCITY_PRICECALCULATE: "INTERCITY_PRICECALCULATE",
  INTERCITY_PRICECALCULATE_SUCESS: "INTERCITY_PRICECALCULATE_SUCESS",
  TRANSITINSURANCE: "TRANSITINSURANCE",
  TRANSITINSURANCE_SUCCESS: "TRANSITINSURANCE_SUCCESS",
  TRANSITINSURANCE_LODING: "TRANSITINSURANCE_LODING",
  LOCAL_COUPON_LIST: "LOCAL_COUPON_LIST",
  OUTSTATION_COUPON_LIST: "OUTSTATION_COUPON_LIST",
};

export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  INFO_REQUEST: "USERS_INFO_REQUEST",
  INFO_SUCCESS: "USERS_INFO_SUCCESS",
  INFO_FAILURE: "USERS_INFO_FAILURE",

  ACCOUNT_HISTORY_REQUEST: "ACCOUNT_HISTORY_REQUEST",
  ACCOUNT_HISTORY_SUCCESS: "ACCOUNT_HISTORY_SUCCESS",
  ACCOUNT_HISTORY_FAILURE: "ACCOUNT_HISTORY_FAILURE",

  REFUND_MONEY_REQUEST: "REFUND_MONEY_REQUEST",
  REFUND_MONEY_SUCCESS: "REFUND_MONEY_SUCCESS",
  REFUND_MONEY_FAILURE: "REFUND_MONEY_FAILURE",

  CCAVENUE_REQ_REQUEST: "CCAVENUE_REQ_REQUEST",
  CCAVENUE_REQ_SUCCESS: "CCAVENUE_REQ_SUCCESS",
  CCAVENUE_REQ_FAILURE: "CCAVENUE_REQ_FAILURE",

  CCAVENUE_RES_REQUEST: "CCAVENUE_RES_REQUEST",
  CCAVENUE_RES_SUCCESS: "CCAVENUE_RES_SUCCESS",
  CCAVENUE_RES_FAILURE: "CCAVENUE_RES_FAILURE",

  TRACKLOAD_REQUEST: "TRACKLOAD_REQUEST",
  TRACKLOAD_SUCCESS: "TRACKLOAD_SUCCESS",
  TRACKLOAD_FAILURE: "TRACKLOAD_FAILURE",

  FEEDBACKLIST_REQUEST: "FEEDBACKLIST_REQUEST",
  FEEDBACKLIST_SUCCESS: "FEEDBACKLIST_SUCCESS",
  FEEDBACKLIST_FAILURE: "FEEDBACKLIST_FAILURE",

  POSTFEEDBACK_SUCCESS: "POSTFEEDBACK_SUCCESS",
  POSTFEEDBACK_FAILURE: "POSTFEEDBACK_FAILURE",

  REFERRAL_REQUEST: "REFERRAL_REQUEST",
  REFERRAL_SUCCESS: "REFERRAL_SUCCESS",
  REFERRAL_FAILURE: "REFERRAL_FAILURE",

  REFERRAL_LIST_REQUEST: "REFERRAL_LIST_REQUEST",
  REFERRAL_LIST_SUCCESS: "REFERRAL_LIST_SUCCESS",
  REFERRAL_LIST_FAILURE: "REFERRAL_LIST_FAILURE",

  CANCELBOOKING_SUCCESS: "CANCELBOOKING_SUCCESS",
  CANCELBOOKING_FAILURE: "CANCELBOOKING_FAILURE",

  DRIVER_REJECT_BOOKING_SUCCESS: "DRIVER_REJECT_BOOKING_SUCCESS",
  DRIVER_REJECT_BOOKING_FAILURE: "DRIVER_REJECT_BOOKING_FAILURE",

  REJECT_REASON_LIST_SUCCESS: "REJECT_LIST_REASON_SUCCESS",

  BIDDING_SUCCESS: "BIDDING_SUCCESS",

  WEBDATA_SUCCESS: "WEBDATA_SUCCESS",

  LOGOUT: "USERS_LOGOUT",
  BACK_TO_FORM: "BACK_TO_FORM",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  CHANGE_BID_AMOUNT: "CHANGE_BID_AMOUNT",
  TRACK_LIST_BID_PROCESS: "TRACK_LIST_BID_PROCESS",
  TRACK_LIST_BID_PROCESS_DRIVER_SEEN: "TRACK_LIST_BID_PROCESS_DRIVER_SEEN",
  BID_PENCIL_CLICK: "BID_PENCIL_CLICK",
  NOTIFY_SUCCESS: "NOTIFY_SUCCESS",
  CROSS_LEAD_SUCCESS: "CROSS_LEAD_SUCCESS",
  CROSS_LEAD_FAILURE: "CROSS_LEAD_FAILURE",
  BACK_TO_CSP_INITIAL_PAGE: "BACK_TO_CSP_INITIAL_PAGE",
  CLEAR_PAY_NOW_DETAILS: "CLEAR_PAY_NOW_DETAILS",
  SECONDARY_NUMBER_LIST_SUCCESS: "SECONDARY_NUMBER_LIST_SUCCESS",
  ADD_SECONDARY_NUMBER_SUCCESS: "ADD_SECONDARY_NUMBER_SUCCESS",
  ADD_SECONDARY_NUMBER_FAILURE: "ADD_SECONDARY_NUMBER_FAILURE",
  JOURNAL_DOWNLOAD_SUCCESS: "JOURNAL_DOWNLOAD_SUCCESS",
  JOURNAL_DOWNLOAD_FAILURE: "JOURNAL_DOWNLOAD_FAILURE",
};

export const booknow = {
  PICKUP_ADDADDRESS: "PICKUP_ADDADDRESS",
  DROP_ADDADDRESS: "DROP_ADDADDRESS",
  LOAD_TYPE: "LOAD_TYPE",
  CHNAGE_PICKUP_ADDADDRESS: "CHNAGE_PICKUP_ADDADDRESS",
  CHNAGE_DROP_ADDADDRESS: "CHNAGE_DROP_ADDADDRESS",
};

export const apiMethods = {
  GETBOOKINGHISTORY_V2: "getbookinghistory_v2",
  COMMUNICATION_UPDATE: "communicationupdate",
};
